# Generated by Django 2.2.4 on 2020-04-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_banner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(help_text='Size: 1920x570', upload_to=''),
        ),
    ]
